### PR TITLE
Construct request details before sending

### LINKED ISSUE #27: Server doesn't reply (SOCKSError), although curl works
I have a socks proxy verified by this command:

`curl -x socks5://<socks_ip>:<socks_port> "http://canihazip.com/"`

When I try to attempt the same thing using ruby socksify gem as per the documentation:

```
require 'socksify/http'
proxy = '<socks_ip>'
port = '<socks_port>'
uri = URI.parse('http://canihazip.com/')
Net::HTTP.SOCKSProxy(proxy, port).start(uri.host, uri.port) do |http|
  http.get(uri.path)
end
```

gives error:

```
/home/resrev/.rvm/gems/ruby-2.2.2/gems/socksify-1.7.0/lib/socksify.rb:269:in `socks_receive_reply':     Server doesn't reply (SOCKSError)
from /home/resrev/.rvm/gems/ruby-2.2.2/gems/socksify-1.7.0/lib/socksify.rb:259:in `socks_connect'
from /home/resrev/.rvm/gems/ruby-2.2.2/gems/socksify-1.7.0/lib/socksify.rb:174:in `initialize'
from /home/resrev/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `open'
from /home/resrev/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
from /home/resrev/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
from /home/resrev/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:878:in `connect'
from /home/resrev/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
from /home/resrev/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:852:in `start'
from /home/resrev/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:583:in `start'
from /home/resrev/pubrevit/lib/tasks/test_rest_client_socks_proxy.rb:51:in `<main>'
```

What am I missing?

```
$ ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [i686-linux]
$ rails --version
Rails 4.2.1
```

### PR DESCRIPTION
**Pull request by sticnarf**
Some SOCKS servers, such as [shadowsocks/shadowsocks](https://github.com/shadowsocks/shadowsocks/tree/master), don't support to read the request details bit by bit.

And according to [RFC 1928](https://www.ietf.org/rfc/rfc1928.txt), it is implied that the request details need constructing before being sending to the server.

This pull request may also resolve #27 .

### CODE REVIEW

**Comment by astro** [comment]
Thank you for your PR.

I'm a bit devastated that such issues occur in the wild. TCP is stream-oriented and does not have *packet boundaries*, therefore shadowsocks is clearly broken? Is the project aware of this?

Could you please clarify if this is just a workaround or do I have a wrong understanding of TCP? I'll merge it then. Do you wish for a new Gem release?

BTW: I haven't actively written Ruby in many years. Would you take over maintainership?

**Comment by sticnarf** [comment]
I agree with you.
I do doubt whether the implementation of shadowsocks is valid. I will consult the maintainer of shadowsocks as to this issue.
I made a PR here because the solution is quite simple and does not make any change in nature (hence no worries about regression). 
As a freshman at university, I do not have enough knowledge of network protocols. So, let me reject the maintainer work for lack of competence. :)

**Comment by sticnarf** [comment]
Now the issue is fixed in [shadowsocks/shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev). The maintainer admits that all current shadowsocks implementations just assume there is no fragmentation on loopback in the handshake stage. 

As to this PR... Merge or close, as you like...

**Comment by astro** [comment]
Published as 1.7.1.

Thank you very much for taking care of this interop problem in both projects. I am happy to follow [Postel's Law](https://en.wikipedia.org/wiki/Robustness_principle)

> As a freshman at university, I do not have enough knowledge of network protocols. So, let me reject the maintainer work for lack of competence. :)

Where else are you going to learn that if not with a tiny library like this one? :)

**Pull request merged**
